apiVersion: v1
kind: Service
metadata:
  name: {{ include "invincible-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "invincible-app.fullname" . }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP